name: tp_dio_retrofit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  retrofit: ^4.1.0
  logger: any  #for logging purpose
  json_annotation: ^4.8.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
